# Generated by Django 2.2.6 on 2020-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200211_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstype',
            name='type_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
